# Generated by Django 3.2.12 on 2025-10-23 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_branch_contactmessage_course_studymaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(default='Default Address'),
        ),
        migrations.CreateModel(
            name='LiveLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lecture_link', models.URLField()),
                ('schedule_time', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.course')),
            ],
        ),
    ]
