# Generated by Django 3.2.12 on 2025-10-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20251023_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name_plural': 'Participants'},
        ),
        migrations.AddField(
            model_name='participant',
            name='registered_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.course'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, default='placeholder@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('phone_number', 'full_name')},
        ),
    ]
